from pathlib import Path
import re

p = Path("index.html")
s = p.read_text(encoding="utf-8")
s = re.sub(r'<style id="finanza-v3-css">.*?</style>\s*', '', s, flags=re.S)
s = re.sub(r'<script id="finanza-v3-js">.*?</script>\s*', '', s, flags=re.S)
s = re.sub(r'<style id="finanza-v4-css">.*?</style>\s*', '', s, flags=re.S)
s = re.sub(r'<script id="finanza-v4-js">.*?</script>\s*', '', s, flags=re.S)

css = r'''<style id="finanza-v4-css">
:root{--linen:#F5F1EA;--khaki:#D7C9B8;--camel:#B2967D;--cocoa:#7D5A44;--espresso:#4A342A;--ink:#4A342A;--bg:#F5F1EA;--paper:#FFFDF9;--line:#DFD4C8;--muted:#806F63;--rose:#B2967D;--rose2:#EADFD4;--blush:#EEE4D9;--gold:#7D5A44;--green:#7F927F;--red:#A96D62}
html,body{background:var(--linen)!important;color:var(--espresso)!important}body,body *{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",Georgia,serif!important;color:var(--espresso)}button,input,select,textarea,a{color:var(--espresso)!important}.nav button,.bottom-nav button,.mobile-nav button{color:var(--espresso)!important}.nav button svg,.bottom-nav button svg,.mobile-nav button svg{stroke:var(--espresso)!important;color:var(--espresso)!important}.top h1,.section h2,.card h2,.login h2,.logo strong,.budget-name,.category-card .big,.metric .value,.metric .amount,.amount,.title{color:var(--espresso)!important}
.budget-overview{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;margin-bottom:14px!important}.budget-stat{min-height:78px!important;padding:11px 12px!important;border:1px solid var(--line)!important;border-radius:17px!important;background:var(--paper)!important;box-shadow:none!important}.budget-stat span{font-size:9px!important;color:var(--muted)!important;font-weight:700!important}.budget-stat b{display:block!important;font-size:18px!important;color:var(--espresso)!important;margin-top:5px}.budget-stat .muted{font-size:9px!important;margin-top:2px}
.budget-category-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px!important}.budget-category-card{padding:13px!important;background:var(--paper)!important;border:1px solid var(--line)!important;border-radius:17px!important}.budget-bar{height:6px!important;background:#E9DDD3!important;border-radius:999px!important;overflow:hidden!important;margin-top:8px!important}.budget-bar i{display:block;height:100%;background:var(--camel)!important;border-radius:999px}.budget-bar i.over{background:var(--espresso)!important}
.finanza-history-shell{height:300px!important;min-height:300px!important;overflow:hidden!important}.finanza-history-shell canvas{display:block!important;width:100%!important;height:270px!important;max-height:270px!important}.finanza-debt-shell{height:270px!important;min-height:270px!important;overflow:hidden!important}.finanza-debt-shell canvas{width:100%!important;height:220px!important;max-height:220px!important}.debt-percent-legend{display:grid;gap:7px;max-height:100px;overflow:auto}.debt-percent-row{display:grid;grid-template-columns:9px 1fr auto;align-items:center;gap:7px;font-size:10px;color:var(--muted)}.debt-percent-row i{width:9px;height:9px;border-radius:50%;display:block}
.finanza-payment-manager{margin-top:14px!important}.finanza-payment-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid var(--line)}.finanza-payment-row:last-child{border-bottom:0}.finanza-payment-main strong{display:block;font-size:12px}.finanza-payment-main small{display:block;color:var(--muted)!important;font-size:10px;margin-top:3px}.finanza-payment-actions{display:flex;gap:7px;align-items:center}.finanza-payment-actions button{font-size:10px!important;padding:7px 10px!important;border-radius:10px!important}.finanza-delete{background:#EAD8D2!important;color:var(--espresso)!important}.finanza-edit{background:var(--rose2)!important;color:var(--espresso)!important}.finanza-empty{font-size:11px;color:var(--muted);padding:10px 0}
.finanza-account-compact{padding:13px!important}.finanza-account-compact .account-balance{font-size:22px!important}.finanza-account-compact .account-meta{font-size:9px!important}.finanza-hide-detail,.finanza-hide-tagline,.finanza-legacy-payments{display:none!important}.finanza-theme-catalog{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-top:10px}.finanza-theme-option{border:1px solid var(--line);border-radius:16px;padding:10px;background:var(--paper);cursor:pointer;text-align:left}.finanza-theme-option.active{outline:2px solid var(--cocoa)}.finanza-theme-swatch{height:48px;border-radius:11px;margin-bottom:8px;display:flex;overflow:hidden}.finanza-theme-swatch i{flex:1}.finanza-theme-option strong{display:block;font-size:11px}.finanza-theme-option small{display:block;color:var(--muted);font-size:9px;margin-top:2px}
@media(max-width:1000px){.budget-overview{grid-template-columns:repeat(2,minmax(0,1fr))!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.finanza-theme-catalog{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:650px){.budget-overview{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.budget-stat{min-height:72px!important;padding:10px!important}.budget-stat b{font-size:17px!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.finanza-history-shell{height:270px!important;min-height:270px!important}.finanza-history-shell canvas{height:240px!important;max-height:240px!important}.finanza-debt-shell{height:auto!important;min-height:0!important}.finanza-payment-row{align-items:flex-start}.finanza-payment-actions{flex-wrap:wrap;justify-content:flex-end}.finanza-theme-catalog{grid-template-columns:repeat(2,minmax(0,1fr))}.grid .metric .value,.grid .metric .amount,.grid .metric b,.metric .value,.metric .amount{color:var(--espresso)!important}}
</style>'''

js = r'''<script id="finanza-v4-js">
(function(){
const THEMES={Cocoa:{bg:'#F5F1EA',paper:'#FFFDF9',ink:'#4A342A',muted:'#806F63',line:'#DFD4C8',rose:'#B2967D',rose2:'#EADFD4',blush:'#EEE4D9',gold:'#7D5A44',green:'#7F927F',red:'#A96D62'},Linen:{bg:'#F5F1EA',paper:'#FFFDF9',ink:'#332C28',muted:'#756A62',line:'#E2DBD2',rose:'#CDBFB0',rose2:'#EEE8DF',blush:'#F1ECE5',gold:'#9F8C78',green:'#7F927F',red:'#A96D62'},Khaki:{bg:'#D7C9B8',paper:'#F8F3EC',ink:'#46372D',muted:'#75665A',line:'#CBBCA9',rose:'#A99076',rose2:'#E9DFD2',blush:'#EEE4D7',gold:'#7D5A44',green:'#71806F',red:'#9C665C'},Camel:{bg:'#B2967D',paper:'#F8F0E7',ink:'#4A342A',muted:'#776254',line:'#D0B9A3',rose:'#A87F5F',rose2:'#E8D8C8',blush:'#EAD7C5',gold:'#7D5A44',green:'#70806E',red:'#9D6258'},Espresso:{bg:'#4A342A',paper:'#F5EEE5',ink:'#4A342A',muted:'#766457',line:'#D7C8B8',rose:'#9B755C',rose2:'#E8D9CA',blush:'#EADBC9',gold:'#6E4B38',green:'#70806E',red:'#9D6258'}};
const root=document.documentElement,esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));function applyTheme(name){const t=THEMES[name]||THEMES.Cocoa;Object.entries(t).forEach(([k,v])=>root.style.setProperty('--'+k,v));localStorage.setItem('finanzaThemeV4',name)}applyTheme(localStorage.getItem('finanzaThemeV4')||'Cocoa');
const num=v=>Number(v)||0;function fmt(n){try{return new Intl.NumberFormat((window.db&&db.language)||'es',{minimumFractionDigits:2,maximumFractionDigits:2}).format(num(n))}catch(e){return num(n).toFixed(2)}}function baseValue(a,c){try{if(typeof convert==='function')return num(convert(a,c,(window.db&&db.baseCurrency)||c))}catch(e){}return num(a)}function mk(d){return String(d||'').slice(0,7)}function ml(k){const[y,m]=k.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString((window.db&&db.language)||'es',{month:'short'}).replace('.','')}function months(n){const a=[],now=new Date();now.setDate(1);for(let i=n-1;i>=0;i--){const d=new Date(now);d.setMonth(now.getMonth()-i);a.push(d.toISOString().slice(0,7))}return a}
function drawHistory(){const c=document.getElementById('finanzaBudgetChart');if(!c||!window.db)return;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(480,r.width||480),h=Math.max(230,r.height||230);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const ms=months(12),total=Object.values(db.budgets||{}).reduce((a,v)=>a+num(v),0),hist=db.budgetHistory||db.budget_history||{},v=ms.map(k=>{let b=hist[k]!=null?(typeof hist[k]==='object'?num(hist[k].total??hist[k].budget):num(hist[k])):total,s=0;(db.transactions||[]).forEach(t=>{if(mk(t.date)===k&&(t.type==='Gasto'||t.type==='Pago de deuda'))s+=baseValue(t.amount,t.currency)});return{b,s}}),max=Math.max(1,...v.flatMap(q=>[q.b,q.s])),L=38,R=12,T=30,B=40,cw=w-L-R,ch=h-T-B,gw=cw/ms.length,bw=Math.max(8,Math.min(20,gw*.27));x.font='700 9px Baskerville,Georgia,serif';x.textAlign='center';v.forEach((q,i)=>{const xx=L+gw*i+gw/2,bh=q.b/max*ch,sh=q.s/max*ch;x.fillStyle=getComputedStyle(root).getPropertyValue('--rose2').trim();x.beginPath();x.roundRect(xx-bw-2,T+ch-bh,bw,bh,4);x.fill();x.fillStyle=getComputedStyle(root).getPropertyValue('--rose').trim();x.beginPath();x.roundRect(xx+2,T+ch-sh,bw,sh,4);x.fill();x.fillStyle=getComputedStyle(root).getPropertyValue('--muted').trim();x.fillText(ml(ms[i]),xx,T+ch+17)});x.textAlign='left';x.font='800 9px Baskerville,Georgia,serif';x.fillStyle=getComputedStyle(root).getPropertyValue('--rose2').trim();x.fillRect(L,8,9,9);x.fillStyle=getComputedStyle(root).getPropertyValue('--ink').trim();x.fillText('Presupuestado',L+14,16);x.fillStyle=getComputedStyle(root).getPropertyValue('--rose').trim();x.fillRect(L+105,8,9,9);x.fillStyle=getComputedStyle(root).getPropertyValue('--ink').trim();x.fillText('Gastado',L+119,16)}
function drawDebt(){const c=document.getElementById('finanzaDebtChart');if(!c||!window.db)return;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(280,r.width||280),h=220;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const g=['Préstamos','Tarjetas','Otros'],v=g.map(q=>(db.debts||[]).filter(d=>String(d.group||'Otros')===q).reduce((a,d)=>a+Math.max(0,baseValue(d.balance??d.saldo,d.currency)),0)),total=v.reduce((a,z)=>a+z,0),cs=['#B2967D','#7D5A44','#7F927F'];let a=-Math.PI/2,cx=Math.min(100,w*.28),cy=h/2,rad=Math.min(68,h/2-12);if(!total){x.fillStyle='#806F63';x.textAlign='center';x.font='12px Baskerville,Georgia,serif';x.fillText('Sin deudas registradas',cx,cy);return}v.forEach((z,i)=>{if(z<=0)return;const q=z/total*Math.PI*2;x.beginPath();x.arc(cx,cy,rad,a,a+q);x.lineWidth=28;x.strokeStyle=cs[i];x.stroke();a+=q});x.beginPath();x.arc(cx,cy,rad*.57,0,Math.PI*2);x.fillStyle=getComputedStyle(root).getPropertyValue('--paper').trim();x.fill();x.fillStyle=getComputedStyle(root).getPropertyValue('--ink').trim();x.textAlign='center';x.font='900 12px Baskerville,Georgia,serif';x.fillText('100%',cx,cy+4);const lg=document.getElementById('debtPercentLegend');if(lg)lg.innerHTML=g.map((q,i)=>v[i]>0?`<div class="debt-percent-row"><i style="background:${cs[i]}"></i><span>${q}</span><b>${(v[i]/total*100).toFixed(1)}%</b></div>`:'').join('')}
function editPayment(id){const p=(db.payments||[]).find(q=>String(q.id)===String(id));if(!p)return;const n=prompt('Nombre de la responsabilidad/cuota:',p.name||'');if(n===null)return;const a=prompt('Importe mensual:',p.amount??'');if(a===null)return;const f=prompt('Fecha de pago (YYYY-MM-DD):',p.dueDate||'');if(f===null)return;p.name=n.trim()||'Responsabilidad de pago';p.amount=num(a);p.dueDate=f.trim();if(typeof save==='function')save();if(typeof render==='function')render()}window.finanzaEditPaymentV4=editPayment;window.finanzaDeletePaymentV4=function(id){const p=(db.payments||[]).find(q=>String(q.id)===String(id));if(!p)return;if(!confirm(`¿Eliminar "${p.name||'Responsabilidad de pago'}"?`))return;db.payments=(db.payments||[]).filter(q=>String(q.id)!==String(id));if(typeof save==='function')save();if(typeof render==='function')render()};
function unifiedPayments(){const c=document.getElementById('content');if(!c||!window.db)return;[...c.querySelectorAll('.card,.panel,.section')].forEach(sec=>{if(sec.id==='finanzaUnifiedPayments')return;const tx=(sec.innerText||'').toLowerCase();if(tx.includes('responsabilidades activas')||tx.includes('responsabilidades de pago'))sec.classList.add('finanza-legacy-payments')});let box=document.getElementById('finanzaUnifiedPayments');if(!box){box=document.createElement('div');box.id='finanzaUnifiedPayments';box.className='card finanza-payment-manager';c.appendChild(box)}const rows=(db.payments||[]).map(p=>`<div class="finanza-payment-row"><div class="finanza-payment-main"><strong>${esc(p.name||'Responsabilidad de pago')}</strong><small>${p.dueDate?'Fecha de pago: '+esc(p.dueDate)+' · ':''}${p.frequency?esc(p.frequency)+' · ':''}${p.amount!=null?fmt(p.amount)+' '+esc(p.currency||db.baseCurrency||''):''}</small></div><div class="finanza-payment-actions"><button class="btn small finanza-edit" onclick="finanzaEditPaymentV4(${JSON.stringify(p.id)})">Editar</button><button class="btn small finanza-delete" onclick="finanzaDeletePaymentV4(${JSON.stringify(p.id)})">Eliminar</button></div></div>`).join('');box.innerHTML=`<div class="section-head"><div><h2>Responsabilidades de pago</h2><div class="muted">Cuotas y responsabilidades mensuales en un solo lugar.</div></div></div>${rows||'<div class="finanza-empty">No tienes responsabilidades de pago registradas.</div>'}`}
function compactAccounts(){const c=document.getElementById('content');if(!c)return;[...c.querySelectorAll('.card,.panel,.section')].forEach(q=>{const t=(q.innerText||'').toLowerCase();if(t.includes('dinero disponible')||t.includes('disponible total'))q.classList.add('finanza-account-compact')})}
function hideTexts(){[...document.querySelectorAll('h1,h2,h3,h4,p,span,div')].forEach(e=>{const t=(e.textContent||'').trim().toLowerCase();if(t==='detalle por moneda original'){e.classList.add('finanza-hide-detail');const card=e.closest('.card,.panel,.section');if(card)card.classList.add('finanza-hide-detail')}if(t==='pequeñas decisiones, grandes resultados'||t==='pequeñas decisiones grandes resultados')e.classList.add('finanza-hide-tagline')})}
function menuFix(){[...document.querySelectorAll('button,a')].forEach(e=>{const t=(e.textContent||'').replace(/\s+/g,' ').trim();if(/^Deudas$/i.test(t)){if(e.closest('.nav'))e.innerHTML='<span aria-hidden="true" style="display:inline-flex;width:18px;justify-content:center">▣</span><span>Deudas</span>';else{const b=[...document.querySelectorAll('.nav button,.nav a')].find(q=>/^Presupuesto$/i.test((q.textContent||'').replace(/\s+/g,' ').trim()));e.innerHTML='<span aria-hidden="true">▥</span><span>Presupuesto</span>';e.onclick=function(ev){ev.preventDefault();if(b)b.click()}}e.style.color=getComputedStyle(root).getPropertyValue('--espresso')}})}
function themeCatalog(){const c=document.getElementById('content');if(!c)return;const h=(c.innerText||'').toLowerCase();if(!h.includes('configuración')&&!h.includes('configuracion'))return;let box=document.getElementById('finanzaThemeCatalog');if(box)box.remove();box=document.createElement('div');box.id='finanzaThemeCatalog';box.className='card';const cur=localStorage.getItem('finanzaThemeV4')||'Cocoa';box.innerHTML='<div class="section-head"><div><h2>Paleta y tipografía</h2><div class="muted">Catálogo visual · Cocoa es la preferencia predeterminada.</div></div></div><div class="finanza-theme-catalog">'+Object.entries(THEMES).map(([n,t])=>`<button class="finanza-theme-option ${n===cur?'active':''}" data-theme="${n}"><span class="finanza-theme-swatch"><i style="background:${t.bg}"></i><i style="background:${t.rose}"></i><i style="background:${t.gold}"></i><i style="background:${t.ink}"></i></span><strong>${n}</strong><small>${n===cur?'Seleccionada':'Aplicar'}</small></button>`).join('')+'</div>';c.appendChild(box);box.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{applyTheme(b.dataset.theme);themeCatalog()})}
function enhance(){try{menuFix();hideTexts();compactAccounts();unifiedPayments();drawHistory();drawDebt();themeCatalog()}catch(e){console.warn('Finanza V4',e)}}const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(enhance,60);return r};let busy=false;new MutationObserver(()=>{if(busy)return;busy=true;setTimeout(()=>{busy=false;enhance()},100)}).observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',()=>{clearTimeout(window.__finanzaV4Resize);window.__finanzaV4Resize=setTimeout(()=>{drawHistory();drawDebt()},120)});setTimeout(enhance,700);
})();
</script>'''

s = s.replace('</head>', css + '</head>', 1)
s = s.replace('</body>', js + '</body>', 1)
p.write_text(s, encoding='utf-8')
