from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
css=r'''
<style id="finanza-requested-fixes">
/* Presupuesto y gráficos: compacto, histórico y responsive */
.dashboard-grid-3{grid-template-columns:1.35fr 1fr 1fr!important;align-items:stretch!important}
.dash-panel{min-height:0!important}
.dash-panel .chart-box{height:220px!important;min-height:0!important}
.dash-panel .chart-canvas{height:220px!important;max-height:220px!important}
#finanzaDebtChart{height:190px!important;max-height:190px!important}
.debt-percent-legend{max-height:120px;overflow:auto}
.budget-overview{grid-template-columns:repeat(4,minmax(0,1fr))!important}
.budget-stat{min-width:0;padding:13px!important}
.budget-stat b{font-size:20px!important}
.budget-category-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}
.budget-category-card{min-width:0;padding:13px;border:1px solid var(--line);border-radius:16px;background:var(--paper)}
.budget-category-card .budget-name{font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.budget-category-card .budget-number{font-size:18px;font-weight:950;margin:5px 0}
.budget-category-card .budget-meta{font-size:10px;color:var(--muted)}
.budget-category-card .budget-bar{height:7px;margin-top:8px}
.budget-history-wrap{height:245px!important;min-height:0!important}
.budget-history-wrap canvas{height:245px!important;max-height:245px!important}
@media(max-width:1000px){.dashboard-grid-3{grid-template-columns:1fr 1fr!important}.budget-overview{grid-template-columns:repeat(2,minmax(0,1fr))!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:650px){.dashboard-grid-3{grid-template-columns:1fr!important}.budget-overview{grid-template-columns:1fr 1fr!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.budget-stat{padding:11px!important}.budget-stat b{font-size:17px!important}.dash-panel .chart-box{height:210px!important}.dash-panel .chart-canvas{height:210px!important}#finanzaDebtChart{height:165px!important;max-height:165px!important}}
</style>
'''
if 'id="finanza-requested-fixes"' not in s:
    s=s.replace('</head>',css+'</head>',1)
js=r'''
<script id="finanza-requested-js">
/* Histórico de presupuesto: se conserva un snapshot mensual. Los meses sin snapshot muestran 0 asignado. */
function finanzaMonthKey(offset){let d=new Date();d.setDate(1);d.setMonth(d.getMonth()+offset);return d.toISOString().slice(0,7)}
function finanzaMonthLabel(key){let d=new Date(key+'-01T00:00:00');return d.toLocaleDateString(db?.language||'es',{month:'short'}).replace('.','')}
function budgetMonthlySpent(cur,month){return (db.transactions||[]).filter(t=>(t.type==='Gasto'||t.type==='Pago de deuda')&&String(t.date||'').startsWith(month)).reduce((a,t)=>a+convert(t.amount,t.currency,cur),0)}
function budgetMonthlyTotal(cur,month){let h=db.budgetHistory?.[month];if(h&&Number.isFinite(Number(h.total)))return h.currency&&h.currency!==cur?convert(h.total,h.currency,cur):Number(h.total)||0;if(month===today().slice(0,7))return Object.values(db.budgets||{}).reduce((a,v)=>a+(Number(v)||0),0);return 0}
function renderBudgetVsSpentChart(cur){const c=$('finanzaBudgetChart');if(!c)return;const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(320,r.width),h=Math.max(210,r.height);c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const months=[];for(let i=-11;i<=0;i++){const k=finanzaMonthKey(i);months.push({key:k,label:finanzaMonthLabel(k)})}const vals=months.map(m=>({budget:budgetMonthlyTotal(cur,m.key),spent:budgetMonthlySpent(cur,m.key)}));const max=Math.max(1,...vals.flatMap(v=>[v.budget,v.spent]));const left=28,right=10,top=28,bottom=34,cw=w-left-right,ch=h-top-bottom,gw=cw/months.length,bw=Math.max(4,Math.min(11,gw*.28));ctx.font='700 9px sans-serif';ctx.textAlign='center';vals.forEach((v,i)=>{const x=left+gw*i+gw/2,bh=v.budget/max*ch,sh=v.spent/max*ch;ctx.fillStyle=finanzaThemeColor('--rose2','#f0e2df');if(bh){ctx.beginPath();ctx.roundRect(x-bw-1,top+ch-bh,bw,bh,4);ctx.fill()}ctx.fillStyle=finanzaThemeColor('--rose','#dba8a1');if(sh){ctx.beginPath();ctx.roundRect(x+1,top+ch-sh,bw,sh,4);ctx.fill()}ctx.fillStyle=finanzaThemeColor('--muted','#8a7e79');ctx.fillText(months[i].label,x,top+ch+16)});ctx.textAlign='left';ctx.font='800 9px sans-serif';ctx.fillStyle=finanzaThemeColor('--rose2','#f0e2df');ctx.fillRect(left,7,9,9);ctx.fillStyle=finanzaThemeColor('--ink','#302b2a');ctx.fillText('Presupuesto',left+13,15);ctx.fillStyle=finanzaThemeColor('--rose','#dba8a1');ctx.fillRect(left+90,7,9,9);ctx.fillStyle=finanzaThemeColor('--ink','#302b2a');ctx.fillText('Gastado',left+103,15)}
function renderDebtChart(){const c=$('finanzaDebtChart');if(!c)return;const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(300,r.width),h=Math.max(165,r.height);c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const groups=['Préstamos','Tarjetas','Otros'],vals=groups.map(g=>(db.debts||[]).filter(d=>debtGroup(d)===g).reduce((a,d)=>a+Math.max(0,eqBase(debtBalance(d),d.currency)),0)),total=vals.reduce((a,v)=>a+v,0);const colors=[finanzaThemeColor('--rose','#dba8a1'),finanzaThemeColor('--gold','#b99460'),finanzaThemeColor('--green','#789b83')];let legend=$('debtPercentLegend');if(!total){if(legend)legend.innerHTML='<div class="notice">No hay saldo de deuda registrado.</div>';ctx.fillStyle=finanzaThemeColor('--muted','#8a7e79');ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText('Sin saldo de deuda',w/2,h/2);return}const cx=Math.min(85,w*.22),cy=Math.min(h/2,82),radius=Math.min(62,h/2-14),inner=radius*.58;let a=-Math.PI/2;vals.forEach((v,i)=>{const delta=v/total*Math.PI*2;ctx.beginPath();ctx.arc(cx,cy,radius,a,a+delta);ctx.lineWidth=22;ctx.strokeStyle=colors[i];ctx.stroke();a+=delta});ctx.beginPath();ctx.arc(cx,cy,inner,0,Math.PI*2);ctx.fillStyle=finanzaThemeColor('--paper','#fffdfc');ctx.fill();ctx.fillStyle=finanzaThemeColor('--ink','#302b2a');ctx.textAlign='center';ctx.font='900 12px sans-serif';ctx.fillText('100%',cx,cy+4);if(legend)legend.innerHTML=groups.map((g,i)=>`<div class="debt-percent-row"><i style="background:${colors[i]}"></i><span>${g}</span><b>${(vals[i]/total*100).toFixed(1)}%</b></div>`).join('')}
function saveBudgetHistorySnapshot(){const month=today().slice(0,7);db.budgetHistory=db.budgetHistory||{};db.budgetHistory[month]={currency:db.budgetCurrency||db.baseCurrency,total:Object.values(db.budgets||{}).reduce((a,b)=>a+(Number(b)||0),0),categories:clone(db.budgets||{})}}
function deleteBudgetCategory(name){if(!Object.prototype.hasOwnProperty.call(db.budgets,name))return;if(!confirm(`¿Eliminar la categoría “${name}”? Los movimientos históricos se conservarán.`))return;delete db.budgets[name];saveBudgetHistorySnapshot();save();closeModal();render()}
function budget(){let month=today().slice(0,7),cur=db.budgetCurrency||db.baseCurrency,catTotal=Object.values(db.budgets||{}).reduce((a,v)=>a+(Number(v)||0),0),spent=budgetMonthlySpent(cur,month),total=catTotal,pct=total?spent/total*100:0;let cards=Object.entries(db.budgets||{}).map(([name,limit])=>{let used=db.transactions.filter(t=>(t.type==='Gasto'||t.type==='Pago de deuda')&&String(t.date||'').startsWith(month)&&t.category===name).reduce((a,t)=>a+convert(t.amount,t.currency,cur),0),p=Number(limit)?used/Number(limit)*100:0;return `<div class="budget-category-card"><div class="budget-name">${name}</div><div class="budget-number">${budgetMoney(Number(limit)||0,cur)}</div><div class="budget-meta">Gastado: ${budgetMoney(used,cur)} · ${p.toFixed(0)}%</div><div class="budget-bar"><i class="${p>100?'over':''}" style="width:${Math.min(100,p)}%"></i></div></div>`}).join('');$('content').innerHTML=`<div class="budget-overview"><div class="budget-stat"><span>Presupuesto total del mes</span><b>${budgetMoney(total,cur)}</b><div class="muted">Categorías</div></div><div class="budget-stat"><span>Gastado este mes</span><b>${budgetMoney(spent,cur)}</b><div class="muted">Gastos + pagos registrados</div></div><div class="budget-stat"><span>Ejecución</span><b class="budget-status ${pct>100?'over':'ok'}">${pct.toFixed(0)}%</b><div class="muted">${pct>100?`Exceso ${(pct-100).toFixed(0)}%`:`${Math.max(0,100-pct).toFixed(0)}% disponible`}</div></div><div class="budget-stat"><span>Disponible del presupuesto</span><b class="budget-status ${total-spent<0?'over':'ok'}">${budgetMoney(Math.max(0,total-spent),cur)}</b><div class="budget-bar"><i class="${pct>100?'over':''}" style="width:${Math.min(100,pct)}%"></i></div></div></div><div class="card"><div class="section-head"><div><h2>Presupuesto mensual</h2><div class="muted">Moneda: ${cur}. Las cuotas y responsabilidades se gestionan desde Pagos.</div></div><div style="display:flex;gap:7px;flex-wrap:wrap"><select class="btn" onchange="setBudgetCurrency(this.value)">${currencyCodes().map(c=>`<option value="${c}" ${c===cur?'selected':''}>${c} · ${currencyName(c)}</option>`).join('')}</select><button class="btn" onclick="addBudgetCategory()">＋ Categoría</button><button class="btn rose" onclick="editBudget()">Editar</button></div></div><div class="budget-category-grid">${cards||'<div class="success">No tienes categorías de presupuesto.</div>'}</div></div>`}
function editBudget(){let rows=Object.entries(db.budgets||{}),cur=db.budgetCurrency||db.baseCurrency,curOpts=currencyCodes().map(c=>`<option value="${c}" ${c===cur?'selected':''}>${c} · ${currencyName(c)}</option>`).join('');let html='<h2>Editar presupuesto</h2><div class="field full"><label>Moneda del presupuesto</label><select id="b_currency">'+curOpts+'</select></div><div class="form">'+rows.map(([c,v])=>`<div class="field"><label>${c}</label><div style="display:flex;gap:6px"><input style="flex:1" id="b_${c.replace(/\W/g,'_')}" type="number" step="0.01" value="${v}"><button type="button" class="btn small" onclick="deleteBudgetCategory(${JSON.stringify(c)})">Eliminar</button></div></div>`).join('')+'</div><div class="notice">Eliminar una categoría solo la quita del presupuesto. Los movimientos históricos se conservan.</div><div class="modal-foot"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn rose" onclick="saveBudget()">Guardar</button></div>';openModal(html)}
function saveBudgetCategory(){let name=$('b_new_name').value.trim(),value=Number($('b_new_value').value)||0;if(!name)return alert('Escribe un nombre para la categoría.');if(db.budgets[name]!==undefined)return alert('Esa categoría ya existe.');if(value<=0)return alert('El presupuesto debe ser mayor que 0. Para eliminar usa Eliminar.');db.budgets[name]=value;saveBudgetHistorySnapshot();save();closeModal();render()}
function saveBudget(){let next=$('b_currency')?.value||db.budgetCurrency||db.baseCurrency,old=db.budgetCurrency||db.baseCurrency;Object.keys(db.budgets||{}).forEach(c=>{let el=$('b_'+c.replace(/\W/g,'_'));if(el){let v=Number(el.value)||0;if(v<=0)delete db.budgets[c];else db.budgets[c]=v}});if(next!==old)Object.keys(db.budgets||{}).forEach(c=>db.budgets[c]=convert(db.budgets[c],old,next));db.budgetCurrency=next;db.expenseSummaryCurrency=next;saveBudgetHistorySnapshot();save();closeModal();render()}
const __finanzaLoginScreen=loginScreen;window.loginScreen=function(){__finanzaLoginScreen();if(loginMode==='new'){let form=document.querySelector('#login .form');if(form&&!document.getElementById('lg_currency')){let d=document.createElement('div');d.className='field full';d.innerHTML='<label>Moneda de preferencia</label><select id="lg_currency">'+Object.keys(DEFAULT_CURRENCIES).map(c=>`<option value="${c}" ${c==='EUR'?'selected':''}>${c} · ${DEFAULT_CURRENCIES[c].name}</option>`).join('')+'</select>';form.appendChild(d)}}}
const __finanzaCreateAccount=createAccount;window.createAccount=async function(){await __finanzaCreateAccount();if(user&&db&&loginMode!=='new'){let c=document.getElementById('lg_currency')?.value||db.baseCurrency||'EUR';db.preferredCurrency=c;db.baseCurrency=c;db.budgetCurrency=c;db.expenseSummaryCurrency=c;db.profile.preferredCurrency=c;save()}}
/* Guarda un snapshot al entrar a Presupuesto para que el mes actual quede registrado. */
const __finanzaGo=go;window.go=function(p,push=true){__finanzaGo(p,push);if(normalizePage(p)==='Presupuesto'&&db){saveBudgetHistorySnapshot();localStorage.setItem(keyDb(user.username),JSON.stringify(db))}}
</script>
'''
if 'id="finanza-requested-js"' not in s:
    s=s.replace('</script></body></html>',js+'</script></body></html>',1)
p.write_text(s,encoding='utf-8')
print('patched',p.stat().st_size)
