from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')
s = re.sub(r'<style id="finanza-v3-css">.*?</style>\s*', '', s, count=1, flags=re.S)
s = re.sub(r'<script id="finanza-v3-js">.*?</script>\s*', '', s, count=1, flags=re.S)

css = r'''<style id="finanza-v3-css">
:root{--linen:#f5f1ea;--khaki:#d7c9b8;--camel:#b2967d;--cocoa:#7d5a44;--espresso:#4a342a;--ink:#4a342a;--bg:var(--linen);--paper:#fffdf9;--line:#dfd4c8;--muted:#806f63;--rose:var(--camel);--rose2:#eadfd4;--blush:#eee4d9;--gold:var(--cocoa);--green:#7f927f;--red:#a96d62}
body{background:radial-gradient(circle at 90% 0,rgba(178,150,125,.22),transparent 30%),var(--linen)!important;color:var(--espresso)!important;font-family:Baskerville,"Iowan Old Style","Palatino Linotype",Georgia,serif!important}
body button,body input,body select,body textarea{font-family:inherit!important;color:var(--espresso)}
.top h1,.section h2,.card h2,.login h2,.logo strong,.budget-name,.category-card .big,.metric .value,.metric .amount,.amount,.title{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",Georgia,serif!important;color:var(--espresso)!important}
.monogram{background:var(--cocoa) url('/icon.svg') center/78% no-repeat!important;color:transparent!important;letter-spacing:0!important}
.logo .monogram{box-shadow:0 8px 22px rgba(74,52,42,.18)}
.budget-overview{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important;margin-bottom:14px!important}
.budget-stat{min-height:82px!important;padding:12px 13px!important;border:1px solid var(--line)!important;border-radius:17px!important;background:var(--paper)!important;box-shadow:none!important}
.budget-stat span{font-size:9px!important;color:var(--muted)!important;font-weight:800!important}.budget-stat b{display:block!important;font-size:18px!important;color:var(--espresso)!important;margin-top:5px}.budget-stat .muted{font-size:9px!important;margin-top:2px}
.budget-category-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px!important}.budget-category-card{padding:13px!important;background:var(--paper)!important;border:1px solid var(--line)!important;border-radius:17px!important}.budget-bar{height:6px!important;background:#e9ddd3!important;border-radius:999px!important;overflow:hidden!important;margin-top:8px!important}.budget-bar i{display:block;height:100%;background:var(--camel)!important;border-radius:999px}.budget-bar i.over{background:var(--espresso)!important}
.finanza-payment-manager{margin-top:14px!important}.finanza-payment-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid var(--line)}.finanza-payment-row:last-child{border-bottom:0}.finanza-payment-main strong{display:block;font-size:12px}.finanza-payment-main small{display:block;color:var(--muted);font-size:10px;margin-top:3px}.finanza-payment-actions{display:flex;gap:7px;align-items:center}.finanza-delete{background:#ead8d2!important;color:var(--espresso)!important}
.finanza-chart-shell{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:12px;align-items:center}.finanza-chart-shell canvas{width:100%!important;height:220px!important;max-height:220px!important}.debt-percent-legend,.finanza-expense-legend{display:grid;gap:7px;max-height:190px;overflow:auto}.debt-percent-row{display:grid;grid-template-columns:10px 1fr auto;align-items:center;gap:7px;font-size:10px;color:var(--muted)}.debt-percent-row i{width:9px;height:9px;border-radius:50%;display:block}#finanzaDebtChart{height:220px!important;max-height:220px!important}
.finanza-theme-catalog{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-top:10px}.finanza-theme-option{border:1px solid var(--line);border-radius:16px;padding:10px;background:var(--paper);cursor:pointer;text-align:left}.finanza-theme-option.active{outline:2px solid var(--cocoa)}.finanza-theme-swatch{height:48px;border-radius:11px;margin-bottom:8px;display:flex;overflow:hidden}.finanza-theme-swatch i{flex:1}.finanza-theme-option strong{display:block;font-size:11px}.finanza-theme-option small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.finanza-font-note{font-size:10px;color:var(--muted);margin-top:8px}
@media(max-width:1000px){.budget-overview{grid-template-columns:repeat(2,minmax(0,1fr))!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.finanza-theme-catalog{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:650px){.budget-overview{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.budget-stat{min-height:74px!important;padding:10px!important}.budget-stat b{font-size:17px!important}.budget-category-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.grid .metric .value,.grid .metric .amount,.grid .metric b,.metric .value,.metric .amount{color:var(--espresso)!important}.finanza-chart-shell{grid-template-columns:1fr}.finanza-chart-shell canvas{height:200px!important;max-height:200px!important}.finanza-payment-row{align-items:flex-start}.finanza-payment-actions{flex-direction:column}.finanza-theme-catalog{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>'''

js = r'''<script id="finanza-v3-js">
(function(){
 const themes={Cocoa:{bg:'#f5f1ea',paper:'#fffdf9',ink:'#4a342a',muted:'#806f63',line:'#dfd4c8',rose:'#b2967d',rose2:'#eadfd4',blush:'#eee4d9',gold:'#7d5a44',green:'#7f927f',red:'#a96d62'},Linen:{bg:'#f5f1ea',paper:'#fffdf9',ink:'#332c28',muted:'#756a62',line:'#e2dbd2',rose:'#cdbfb0',rose2:'#eee8df',blush:'#f1ece5',gold:'#9f8c78',green:'#7f927f',red:'#a96d62'},Khaki:{bg:'#d7c9b8',paper:'#f8f3ec',ink:'#46372d',muted:'#75665a',line:'#cbbca9',rose:'#a99076',rose2:'#e9dfd2',blush:'#eee4d7',gold:'#7d5a44',green:'#71806f',red:'#9c665c'},Camel:{bg:'#b2967d',paper:'#f8f0e7',ink:'#4a342a',muted:'#776254',line:'#d0b9a3',rose:'#a87f5f',rose2:'#e8d8c8',blush:'#ead7c5',gold:'#7d5a44',green:'#70806e',red:'#9d6258'},Espresso:{bg:'#4a342a',paper:'#f5eee5',ink:'#4a342a',muted:'#766457',line:'#d7c8b8',rose:'#9b755c',rose2:'#e8d9ca',blush:'#eadbc9',gold:'#6e4b38',green:'#70806e',red:'#9d6258'}};
 const applyTheme=name=>{const t=themes[name]||themes.Cocoa;const r=document.documentElement;Object.entries(t).forEach(([k,v])=>r.style.setProperty('--'+k,v));localStorage.setItem('finanzaThemeV3',name)};applyTheme(localStorage.getItem('finanzaThemeV3')||'Cocoa');
 function moneyV3(n){try{return new Intl.NumberFormat(db?.language||'es',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}catch(e){return (Number(n)||0).toFixed(2)}}function col(v,f){return getComputedStyle(document.documentElement).getPropertyValue(v).trim()||f}
 function donut(canvas,labels,vals,legendId){if(!canvas)return;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(300,r.width||300),h=Math.max(180,r.height||180);canvas.width=w*d;canvas.height=h*d;const x=canvas.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const total=vals.reduce((a,v)=>a+v,0),cs=[col('--rose','#b2967d'),col('--gold','#7d5a44'),col('--green','#7f927f'),'#9b806d','#6f5a4b','#a58f7a','#8b6b55','#6b4a3a'];let lg=document.getElementById(legendId);if(!total){x.fillStyle=col('--muted','#806f63');x.textAlign='center';x.font='12px Baskerville,Georgia,serif';x.fillText('Sin datos registrados',w/2,h/2);if(lg)lg.innerHTML='<div class="notice">No hay datos registrados.</div>';return}const cx=Math.min(88,w*.24),cy=h/2,rad=Math.min(68,h/2-12),inn=rad*.57;let a=-Math.PI/2;vals.forEach((v,i)=>{if(v<=0)return;const z=v/total*Math.PI*2;x.beginPath();x.arc(cx,cy,rad,a,a+z);x.lineWidth=24;x.strokeStyle=cs[i%cs.length];x.stroke();a+=z});x.beginPath();x.arc(cx,cy,inn,0,Math.PI*2);x.fillStyle=col('--paper','#fffdf9');x.fill();x.fillStyle=col('--ink','#4a342a');x.textAlign='center';x.font='900 12px Baskerville,Georgia,serif';x.fillText('100%',cx,cy+4);if(lg)lg.innerHTML=labels.map((q,i)=>vals[i]>0?`<div class="debt-percent-row"><i style="background:${cs[i%cs.length]}"></i><span>${q}</span><b>${(vals[i]/total*100).toFixed(1)}%</b></div>`:'').join('')}
 window.renderDebtChart=function(){const c=document.getElementById('finanzaDebtChart');if(!c||!window.db)return;const gs=['Préstamos','Tarjetas','Otros'];const vs=gs.map(g=>(db.debts||[]).filter(d=>String(d.group||'Otros')===g).reduce((a,d)=>a+Math.max(0,Number(typeof eqBase==='function'?eqBase(debtBalance(d),d.currency):d.balance||0)||0),0));donut(c,gs,vs,'debtPercentLegend')};
 window.renderExpenseCategoryChartV3=function(){if(!window.db)return;let c=['finanzaCategoryChart','expenseCategoryChart','finanzaExpenseCategoryChart'].map(id=>document.getElementById(id)).find(Boolean);if(!c)c=[...document.querySelectorAll('canvas')].find(q=>((q.closest('.card,.dash-panel,.panel,.section')||q.parentElement)?.innerText||'').toLowerCase().includes('gastos por categor'));if(!c)return;const cur=db.baseCurrency,m=today().slice(0,7),map={};(db.transactions||[]).filter(t=>t.type==='Gasto'&&String(t.date||'').startsWith(m)).forEach(t=>{const k=t.category||'Otros';map[k]=(map[k]||0)+(typeof convert==='function'?convert(t.amount,t.currency,cur):Number(t.amount)||0)});const e=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);donut(c,e.map(x=>x[0]),e.map(x=>x[1]),'finanzaExpenseLegend')};
 window.renderBudgetVsSpentChart=function(cur){const c=document.getElementById('finanzaBudgetChart');if(!c||!window.db)return;cur=cur||db.budgetCurrency||db.baseCurrency;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(360,r.width||360),h=Math.max(220,r.height||220);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const ms=[];for(let i=-5;i<=0;i++){let z=new Date();z.setDate(1);z.setMonth(z.getMonth()+i);ms.push({k:z.toISOString().slice(0,7),l:z.toLocaleDateString(db?.language||'es',{month:'short'}).replace('.','')})}const total=Object.values(db.budgets||{}).reduce((a,v)=>a+(Number(v)||0),0),spent=(db.transactions||[]).filter(t=>(t.type==='Gasto'||t.type==='Pago de deuda')&&String(t.date||'').startsWith(ms[5].k)).reduce((a,t)=>a+(typeof convert==='function'?convert(t.amount,t.currency,cur):Number(t.amount)||0),0),vals=ms.map((m,i)=>({b:i===5?total:0,s:i===5?spent:0})),mx=Math.max(1,...vals.flatMap(q=>[q.b,q.s])),L=38,R=12,T=30,B=38,cw=w-L-R,ch=h-T-B,gw=cw/ms.length,bw=Math.max(10,Math.min(22,gw*.24));x.font='700 9px Baskerville,Georgia,serif';x.textAlign='center';vals.forEach((q,i)=>{const xx=L+gw*i+gw/2,bh=q.b/mx*ch,sh=q.s/mx*ch;x.fillStyle=col('--rose2','#eadfd4');if(bh){x.beginPath();x.roundRect(xx-bw-2,T+ch-bh,bw,bh,4);x.fill()}x.fillStyle=col('--rose','#b2967d');if(sh){x.beginPath();x.roundRect(xx+2,T+ch-sh,bw,sh,4);x.fill()}x.fillStyle=col('--muted','#806f63');x.fillText(ms[i].l,xx,T+ch+17)});x.textAlign='left';x.font='800 9px Baskerville,Georgia,serif';x.fillStyle=col('--rose2','#eadfd4');x.fillRect(L,8,9,9);x.fillStyle=col('--ink','#4a342a');x.fillText('Presupuesto',L+14,16);x.fillStyle=col('--rose','#b2967d');x.fillRect(L+92,8,9,9);x.fillStyle=col('--ink','#4a342a');x.fillText('Gastado',L+106,16)};
 window.finanzaDeletePaymentV3=function(id){const p=(db.payments||[]).find(q=>String(q.id)===String(id));if(!p)return;if(!confirm(`¿Eliminar la responsabilidad/cuota “${p.name||'Sin nombre'}”?`))return;db.payments=(db.payments||[]).filter(q=>String(q.id)!==String(id));if(typeof save==='function')save();finanzaToastV3('Responsabilidad eliminada','La cuota fue eliminada sin borrar otros movimientos.');if(typeof render==='function')render()};
 function paymentManager(){if(!window.db||!Array.isArray(db.payments))return;const c=document.getElementById('content');if(!c)return;let w=document.getElementById('finanzaPaymentManagerV3');if(!w){w=document.createElement('div');w.id='finanzaPaymentManagerV3';w.className='card finanza-payment-manager';c.appendChild(w)}const rows=db.payments.map(p=>`<div class="finanza-payment-row"><div class="finanza-payment-main"><strong>${p.name||'Responsabilidad de pago'}</strong><small>${p.dueDate?'Fecha de pago: '+p.dueDate+' · ':''}${p.frequency||''}${p.amount!=null?' · '+moneyV3(p.amount):''}${p.currency?' '+p.currency:''}</small></div><div class="finanza-payment-actions"><span class="badge ${p.active===false?'bad':'good'}">${p.active===false?'Inactiva':'Activa'}</span><button class="btn small finanza-delete" onclick="finanzaDeletePaymentV3(${JSON.stringify(p.id)})">Eliminar</button></div></div>`).join('');w.innerHTML=`<div class="section-head"><div><h2>Responsabilidades y cuotas</h2><div class="muted">Elimina cualquier responsabilidad o cuota sin borrar los movimientos históricos.</div></div></div>${rows||'<div class="notice">No hay responsabilidades ni cuotas registradas.</div>'}`}
 function finanzaToastV3(t,b){document.querySelector('.finanza-notify-toast')?.remove();const e=document.createElement('div');e.className='finanza-notify-toast';e.innerHTML=`<strong>${t}</strong><div class="muted" style="margin-top:4px">${b||''}</div>`;document.body.appendChild(e);setTimeout(()=>e.remove(),6000)}function notify(t,b){try{if('Notification'in window&&Notification.permission==='granted')new Notification(t,{body:b,icon:'/icon.svg'})}catch(e){}finanzaToastV3(t,b)}
 async function askNotify(){if(!('Notification'in window)){alert('Este navegador no admite notificaciones.');return}const p=await Notification.requestPermission();if(p==='granted'){finanzaToastV3('Notificaciones activadas','Recibirás avisos de pagos y actividad.');checkNotifications(true)}else finanzaToastV3('Notificaciones no activadas','Puedes habilitarlas desde la configuración del navegador.')};window.finanzaAskNotificationsV3=askNotify;
 function checkNotifications(force){if(!window.db)return;const now=Date.now(),tx=db.transactions||[],sig=tx.map(t=>String(t.id)+'|'+String(t.date)+'|'+String(t.amount)+'|'+String(t.type)).sort().join('||'),key='finanzaNotifyV3';let st;try{st=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){st={}}if(!st.sig){st.sig=sig;st.lastActivity=now;st.lastCheck=now;localStorage.setItem(key,JSON.stringify(st));return}if(sig!==st.sig){st.sig=sig;st.lastActivity=now;st.sent8=false;st.sent24=false;localStorage.setItem(key,JSON.stringify(st));if(!force)notify('Nuevo movimiento registrado','Se detectó un nuevo movimiento en Finanza.');return}const age=now-Number(st.lastActivity||now),day=new Date().toISOString().slice(0,10);if(age>=8*3600000&&!st.sent8){notify('Llevas más de 8 horas sin registrar movimientos','Recuerda actualizar tu situación financiera.');st.sent8=true}if(age>=24*3600000&&!st.sent24){notify('Llevas 1 día sin registrar movimientos','Haz una actualización rápida de tus finanzas.');st.sent24=true}(db.payments||[]).filter(p=>p.active!==false&&p.dueDate&&String(p.dueDate).slice(0,10)===day).forEach(p=>{const k='due:'+day+':'+p.id;if(localStorage.getItem(k)!=='1'){notify('Pago programado hoy',p.name||'Tienes una responsabilidad de pago pendiente.');localStorage.setItem(k,'1')}});localStorage.setItem(key,JSON.stringify(st))}
 function themeCatalog(){const c=document.getElementById('content');if(!c)return;const h=(c.innerText||'').toLowerCase();if(!h.includes('configuración')&&!h.includes('configuracion'))return;let old=document.getElementById('finanzaThemeCatalog');if(old)old.remove();const box=document.createElement('div');box.id='finanzaThemeCatalog';box.className='card';const current=localStorage.getItem('finanzaThemeV3')||'Cocoa';box.innerHTML=`<div class="section-head"><div><h2>Paleta y tipografía</h2><div class="muted">Catálogo visual. Preferencia inicial: Cocoa.</div></div></div><div class="finanza-theme-catalog">${Object.entries(themes).map(([n,t])=>`<button class="finanza-theme-option ${n===current?'active':''}" data-theme="${n}"><span class="finanza-theme-swatch"><i style="background:${t.bg}"></i><i style="background:${t.rose}"></i><i style="background:${t.gold}"></i><i style="background:${t.ink}"></i></span><strong>${n}</strong><small>${n==='Cocoa'?'Preferida':'Aplicar paleta'}</small></button>`).join('')}</div><div class="finanza-font-note">Tipografía serif editorial inspirada en la referencia Linen / Khaki / Camel / Cocoa / Espresso.</div><div style="margin-top:12px"><button class="btn rose" onclick="finanzaAskNotificationsV3()">Activar notificaciones</button></div>`;c.appendChild(box);box.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{applyTheme(b.dataset.theme);themeCatalog()})}
 function enhance(){try{document.querySelectorAll('.nav button').forEach(b=>{const tx=(b.textContent||'').replace(/\s+/g,' ').trim();if(tx.toLowerCase().includes('deudas'))b.textContent='Deudas'});paymentManager();renderExpenseCategoryChartV3();renderDebtChart();renderBudgetVsSpentChart();themeCatalog()}catch(e){console.warn('Finanza V3',e)}}
 const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(enhance,0);return r}}
 new MutationObserver(()=>setTimeout(enhance,0)).observe(document.body,{childList:true,subtree:true});setInterval(()=>checkNotifications(false),5*60*1000);setTimeout(()=>{enhance();checkNotifications(false)},700);window.addEventListener('load',()=>setTimeout(enhance,500));
})();
</script>'''

s = s.replace('</head>', css + '</head>', 1)
s = s.replace('</body>', js + '</body>', 1)
p.write_text(s, encoding='utf-8')
PY