from pathlib import Path
import re
p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=re.sub(r'<style id="finanza-v8-css">.*?</style>\s*','',s,flags=re.S)
s=re.sub(r'<script id="finanza-v8-js">.*?</script>\s*','',s,flags=re.S)
s=s.replace('<div class="logo"><img class="brandmark" src="icon.svg" alt="Finanza"><div><strong>Finanza</strong><small>Tu vida en equilibrio</small></div></div>','<div class="logo"><img class="finanza-full-logo" src="logo.svg" alt="Finanza · Tu vida en equilibrio"></div>')
s=s.replace('<img class="login-logo" src="icon.svg" alt="Finanza">','<img class="login-logo" src="logo.svg" alt="Finanza · Tu vida en equilibrio">')
s=s.replace('<div class="welcome-brand"><img src="icon.svg" alt="Finanza"><div><strong>Finanza</strong><small>Tu vida en equilibrio</small></div></div>','<div class="welcome-brand"><img src="logo.svg" alt="Finanza · Tu vida en equilibrio"></div>')
s=s.replace('<div class="summary-mobile-brand"><img src="icon.svg" alt="Finanza"><div><b>FINANZA</b><span>Tu vida en equilibrio</span></div></div>','<div class="summary-mobile-brand"><img src="logo.svg" alt="Finanza · Tu vida en equilibrio"></div>')
old='<button data-page="Deudas" onclick="go(\'Deudas\')"><i></i><span>Deudas</span></button><button data-page="Ahorro" onclick="go(\'Ahorro\')"><i></i><span>Ahorro</span></button>'
new='<button data-page="Deudas" onclick="go(\'Deudas\')"><i></i><span>Deudas</span></button><button data-page="Presupuesto" onclick="go(\'Presupuesto\')"><i></i><span>Presupuesto</span></button><button data-page="Ahorro" onclick="go(\'Ahorro\')"><i></i><span>Ahorro</span></button>'
if old in s:s=s.replace(old,new,1)
s=s.replace("{Resumen:'home',Movimientos:'move',Cuentas:'account',Deudas:'debt',Ahorro:'saving'}[b.dataset.page]||'home'","{Resumen:'home',Movimientos:'move',Cuentas:'account',Deudas:'debt',Presupuesto:'budget',Ahorro:'saving'}[b.dataset.page]||'home'")
css='''<style id="finanza-v8-css">.finanza-full-logo{display:block;width:188px;height:auto;max-height:112px;object-fit:contain;object-position:left center}.side .logo{align-items:center;min-height:94px}.login-logo{width:270px!important;height:auto!important;max-height:170px!important;object-fit:contain!important;border-radius:0!important;box-shadow:none!important}.welcome-brand img{display:block;width:175px;height:auto;max-height:78px;object-fit:contain}.summary-mobile-brand img{display:block;width:180px;height:auto;max-height:62px;object-fit:contain}.top-date,.dashboard-quote{display:none!important}.top{min-height:0!important}@media(min-width:651px){.top{height:0!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;backdrop-filter:none!important;overflow:visible!important}.top-left{display:none!important}.top .hello{position:fixed;right:24px;top:18px;z-index:70}.main{padding-top:0!important}}@media(max-width:650px){.top{height:48px!important;margin:-15px -14px 8px!important;padding:4px 14px!important;border-bottom:0!important;background:transparent!important;backdrop-filter:none!important}.summary-mobile-brand img{width:150px!important;max-height:44px!important}.primary-bottom{grid-template-columns:repeat(6,1fr)!important}.primary-bottom button{font-size:8.5px!important;padding:4px 1px!important}.primary-bottom i{font-size:20px!important}}</style>'''
js='''<script id="finanza-v8-js">(function(){function fix(){try{const bar=document.getElementById('primaryBottom');if(bar){const debt=bar.querySelector('button[data-page="Deudas"]');const budget=bar.querySelector('button[data-page="Presupuesto"]');if(debt){debt.dataset.page='Deudas';debt.innerHTML='<i></i><span>Deudas</span>';debt.onclick=function(){go('Deudas')}}if(budget){budget.dataset.page='Presupuesto';budget.innerHTML='<i></i><span>Presupuesto</span>';budget.onclick=function(){go('Presupuesto')};budget.setAttribute('aria-label','Presupuesto')}if(typeof nav==='function')nav()}}catch(e){console.warn('Finanza V8',e)}}const oldGo=window.go;if(typeof oldGo==='function'&&!oldGo.__finanzaV8){const g=oldGo;window.go=function(p,push){const r=g.apply(this,arguments);setTimeout(fix,500);return r};window.go.__finanzaV8=true}setTimeout(fix,300);setTimeout(fix,900);setTimeout(fix,1600)})();</script>'''
s=s.replace('</body>',css+'\n'+js+'\n</body>') if '</body>' in s else s+css+js
p.write_text(s,encoding='utf-8')
